# Generated by Django 4.2.3 on 2023-10-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Antivirus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus', models.CharField(max_length=150, unique=True, verbose_name='Versión de antivirus')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='HerramientaCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramienta', models.CharField(max_length=150, unique=True, verbose_name='Herramienta cloud')),
            ],
        ),
        migrations.CreateModel(
            name='Navegador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navegador', models.CharField(max_length=150, unique=True, verbose_name='Navegador web')),
            ],
        ),
        migrations.CreateModel(
            name='Ofimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete_ofimatica', models.CharField(max_length=150, unique=True, verbose_name='Paquete de ofimatica')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(max_length=150, unique=True, verbose_name='nombre del sistema')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='VersionSistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_sistema', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.sistemaoperativo', verbose_name='version sistema operativo')),
            ],
        ),
        migrations.CreateModel(
            name='VersionOfimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=150, unique=True, verbose_name='Version del paquete ofimatica')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.ofimatica')),
            ],
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('serie', models.CharField(max_length=50, verbose_name='Número de serie')),
                ('estado_software', models.BooleanField(default=False)),
                ('estado_hardware', models.BooleanField(default=False)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.estado', verbose_name='Estado')),
                ('usuario_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.antivirus')),
                ('herramienta_cloud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.herramientacloud')),
                ('id_activo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.tipoactivo', verbose_name='Activo')),
                ('navegador_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navegador_1', to='activos.navegador')),
                ('navegador_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navegador_2', to='activos.navegador')),
                ('ofimatica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.ofimatica')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.sistemaoperativo')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('version_ofimatica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.versionofimatica')),
                ('version_sistema_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.versionsistemaoperativo', verbose_name='Versión de sistema operativo')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_madre_marca', models.CharField(max_length=150, verbose_name='Marca motherboard')),
                ('tarjeta_madre_modelo', models.CharField(max_length=150, verbose_name='Modelo motherboard')),
                ('tarjeta_madre_serie', models.CharField(max_length=150, verbose_name='Serie serie motherboard')),
                ('tarjeta_madre_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('fuente_poder_marca', models.CharField(max_length=150, verbose_name='Marca fuente')),
                ('fuente_poder_modelo', models.CharField(max_length=150, verbose_name='Modelo fuente')),
                ('fuente_poder_serie', models.CharField(max_length=150, verbose_name='Serie serie fuente')),
                ('fuente_poder_capacidad', models.IntegerField(verbose_name='capacidad fuente')),
                ('fuente_poder_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('procesador_marca', models.CharField(max_length=150, verbose_name='Marca procesador')),
                ('procesador_modelo', models.CharField(max_length=150, verbose_name='Modelo procesador')),
                ('procesador_serie', models.CharField(max_length=150, verbose_name='Serie procesador')),
                ('procesador_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('disco_duro_1_marca', models.CharField(max_length=150, verbose_name='Marca disco duro 1')),
                ('disco_duro_1_modelo', models.CharField(max_length=150, verbose_name='Modelo disco duro 1')),
                ('disco_duro_1_serie', models.CharField(max_length=150, verbose_name='Serie disco duro 1')),
                ('disco_duro_1_capacidad', models.IntegerField(verbose_name='capacidad disco duro 1')),
                ('disco_duro_1_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('disco_duro_2_marca', models.CharField(max_length=150, verbose_name='Marca disco duro 2')),
                ('disco_duro_2_modelo', models.CharField(max_length=150, verbose_name='Modelo disco duro 2')),
                ('disco_duro_2_serie', models.CharField(max_length=150, verbose_name='Serie disco duro 2')),
                ('disco_duro_2_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('disco_duro_2_capacidad', models.IntegerField(verbose_name='capacidad disco duro 2')),
                ('ram_slot_1_marca', models.CharField(max_length=150, verbose_name='Marca memoria ram 1')),
                ('ram_slot_1_modelo', models.CharField(max_length=150, verbose_name='Modelo memoria ram 1')),
                ('ram_slot_1_serie', models.CharField(max_length=150, verbose_name='Serie memoria ram 1')),
                ('ram_slot_1_capacidad', models.IntegerField(verbose_name='capacidad memoria ram 1')),
                ('ram_slot_1_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('ram_slot_2_marca', models.CharField(max_length=150, verbose_name='Marca memoria ram 2')),
                ('ram_slot_2_modelo', models.CharField(max_length=150, verbose_name='Modelo memoria ram 2')),
                ('ram_slot_2_serie', models.CharField(max_length=150, verbose_name='Serie memoria ram 2')),
                ('ram_slot_2_capacidad', models.IntegerField(verbose_name='capacidad memoria ram 2')),
                ('ram_slot_2_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('tarjeta_video_marca', models.CharField(max_length=150, verbose_name='Marca tarjeta video')),
                ('tarjeta_video_modelo', models.CharField(max_length=150, verbose_name='Modelo tarjeta video')),
                ('tarjeta_video_serie', models.CharField(max_length=150, verbose_name='Serie tarjeta video')),
                ('tarjeta_video_capacidad', models.IntegerField(verbose_name='Capacidad tarjeta video')),
                ('tarjeta_video_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('monitor_marca', models.CharField(max_length=150, verbose_name='Marca monitor')),
                ('monitor_modelo', models.CharField(max_length=150, verbose_name='Modelo monitor')),
                ('monitor_serie', models.CharField(max_length=150, verbose_name='Serie monitor')),
                ('monitor_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('mouse_marca', models.CharField(max_length=150, verbose_name='Marca mouse')),
                ('mouse_modelo', models.CharField(max_length=150, verbose_name='Modelo mouse')),
                ('mouse_serie', models.CharField(max_length=150, verbose_name='Serie mouse')),
                ('mouse_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('teclado_marca', models.CharField(max_length=150, verbose_name='Marca teclado')),
                ('teclado_modelo', models.CharField(max_length=150, verbose_name='Modelo teclado')),
                ('teclado_serie', models.CharField(max_length=150, verbose_name='Serie teclado')),
                ('teclado_no_aplica', models.BooleanField(default=False, verbose_name='No aplica')),
                ('id_activo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.tipoactivo', verbose_name='Activo')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
