# Generated by Django 4.2.3 on 2023-07-12 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionsoftware',
            name='usuario_registro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
