# Generated by Django 4.2.3 on 2023-12-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_madre_serie',
            field=models.CharField(max_length=150, verbose_name='Serie de motherboard'),
        ),
    ]
