# Generated by Django 4.2.3 on 2023-07-21 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_informacionsoftware_usuario_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionsoftware',
            name='antivirus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.antivirus'),
        ),
        migrations.AlterField(
            model_name='informacionsoftware',
            name='herramienta_cloud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.herramientacloud'),
        ),
        migrations.AlterField(
            model_name='informacionsoftware',
            name='id_activo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.tipoactivo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='informacionsoftware',
            name='navegador_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navegador_1', to='activos.navegador'),
        ),
        migrations.AlterField(
            model_name='informacionsoftware',
            name='navegador_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navegador_2', to='activos.navegador'),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='sistema_operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.sistemaoperativo', verbose_name='version sistema operativo'),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='version_sistema',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
