# Generated by Django 4.2.3 on 2024-01-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_informacionhardware_tarjeta_madre_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemaoperativo',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='sistema_operativo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='activos.sistemaoperativo', to_field='nombre_sistema', verbose_name='version sistema operativo'),
        ),
    ]
