# Generated by Django 4.2.3 on 2024-01-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_sistemaoperativo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemaoperativo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='sistema_operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.sistemaoperativo', verbose_name='version sistema operativo'),
        ),
    ]
