# Generated by Django 4.2.3 on 2023-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_informacionsoftware_antivirus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_1_capacidad',
            field=models.CharField(max_length=150, verbose_name='capacidad disco duro 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_1_marca',
            field=models.CharField(max_length=150, verbose_name='Marca disco duro 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_1_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo disco duro 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_1_serie',
            field=models.CharField(max_length=150, verbose_name='Numero disco duro 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_2_capacidad',
            field=models.CharField(max_length=150, verbose_name='capacidad disco duro 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_2_marca',
            field=models.CharField(max_length=150, verbose_name='Marca disco duro 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_2_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo disco duro 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='disco_duro_2_serie',
            field=models.CharField(max_length=150, verbose_name='Numero disco duro 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='fuente_poder_capacidad',
            field=models.CharField(max_length=150, verbose_name='capacidad fuente'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='fuente_poder_marca',
            field=models.CharField(max_length=150, verbose_name='Marca fuente'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='fuente_poder_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo fuente'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='fuente_poder_serie',
            field=models.CharField(max_length=150, verbose_name='Numero serie fuente'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='monitor_marca',
            field=models.CharField(max_length=150, verbose_name='Marca monitor'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='monitor_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo monitor'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='monitor_serie',
            field=models.CharField(max_length=150, verbose_name='Numero monitor'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='mouse_marca',
            field=models.CharField(max_length=150, verbose_name='Marca mouse'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='mouse_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo mouse'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='mouse_serie',
            field=models.CharField(max_length=150, verbose_name='Serie mouse'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='procesador_marca',
            field=models.CharField(max_length=150, verbose_name='Marca procesador'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='procesador_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo procesador'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='procesador_serie',
            field=models.CharField(max_length=150, verbose_name='Numero procesador'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_1_capacidad',
            field=models.CharField(max_length=150, verbose_name='capacidad memoria ram 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_1_marca',
            field=models.CharField(max_length=150, verbose_name='Marca memoria ram 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_1_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo memoria ram 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_1_serie',
            field=models.CharField(max_length=150, verbose_name='Numero memoria ram 1'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_2_capacidad',
            field=models.CharField(max_length=150, verbose_name='capacidad memoria ram 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_2_marca',
            field=models.CharField(max_length=150, verbose_name='Marca memoria ram 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_2_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo memoria ram 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='ram_slot_2_serie',
            field=models.CharField(max_length=150, verbose_name='Numero memoria ram 2'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_madre_marca',
            field=models.CharField(max_length=150, verbose_name='Marca motherboard'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_madre_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo motherboard'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_madre_serie',
            field=models.CharField(max_length=150, verbose_name='Numero serie motherboard'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_video_capacidad',
            field=models.CharField(max_length=150, verbose_name='Capacidad tarjeta video'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_video_marca',
            field=models.CharField(max_length=150, verbose_name='Marca tarjeta video'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_video_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo tarjeta video'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='tarjeta_video_serie',
            field=models.CharField(max_length=150, verbose_name='Numero tarjeta video'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='teclado_marca',
            field=models.CharField(max_length=150, verbose_name='Marca teclado'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='teclado_modelo',
            field=models.CharField(max_length=150, verbose_name='Modelo teclado'),
        ),
        migrations.AlterField(
            model_name='informacionhardware',
            name='teclado_serie',
            field=models.CharField(max_length=150, verbose_name='Serie teclado'),
        ),
    ]
