# Generated by Django 4.2.3 on 2023-10-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_informacionhardware_disco_duro_1_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemaoperativo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='version_sistema',
            field=models.CharField(max_length=150),
        ),
    ]
