# Generated by Django 4.2.3 on 2023-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_alter_sistemaoperativo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemaoperativo',
            name='nombre_sistema',
            field=models.CharField(max_length=150, verbose_name='nombre del sistema'),
        ),
    ]
