# Generated by Django 4.2.3 on 2023-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_alter_sistemaoperativo_nombre_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofimatica',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='versionofimatica',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sistemaoperativo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sistemaoperativo',
            name='nombre_sistema',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre del sistema'),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='versionsistemaoperativo',
            name='version_sistema',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
